package igu;

import com.mycompany.proyecto1ssoo.TableProcessors;

import javax.swing.JOptionPane;
import com.mycompany.proyecto1ssoo.Simulator;
import com.mycompany.proyecto1ssoo.Process;
import com.mycompany.proyecto1ssoo.ProcessPCB;
import com.mycompany.proyecto1ssoo.ProcessQueue;
import com.mycompany.proyecto1ssoo.Processor;
import com.mycompany.proyecto1ssoo.SchedulingPolicy;
import java.awt.Color;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel; 
import java.awt.event.ActionListener; 
import java.awt.event.ActionEvent; 
import javax.swing.JPanel;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.awt.Component;
import javax.swing.DefaultListModel;

/**
 *
 * @author beacardozo
 */
public class MainView extends javax.swing.JFrame {
    private Simulator simulator;
    public boolean isSimulationActive = false; 
    public boolean isSimulationFinished = false;
    public Timer timer;
    
    
    public MainView() {
        initComponents();
        simulator = new Simulator(2,this);
        updateButtonStates(); 
        setTitle("Process Simulator");
        disableJPanel(IOBoundPanel, IOBoundOption.isSelected());
        enablePanels(false);
        GlobalClockSimulationLabel.setText("Global Clock Cycle Number: 0");
        ExecutionModeLabel.setText("");
        totalExecutionTimeLabel.setText("");
        totalClockCyclesLabel.setText("");
        completionRateLabel.setText("");
        MetricPlanningPolicyLabel.setText("");
        nProcessorsLabel.setText("");
        processesFinishedLabel.setText("");
        processesEnteredLabel.setText("");
        updatePanelVisibility(isSimulationFinished);
        ModifySpecificationsButton.setVisible(isSimulationActive);
        for (SchedulingPolicy policy : SchedulingPolicy.values()) {
            SchedulingPolicyComboBox.addItem(policy.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProcessTypeGroup = new javax.swing.ButtonGroup();
        ActiveProcessorsGroup = new javax.swing.ButtonGroup();
        ConfigPanel = new javax.swing.JPanel();
        ProcessDetailsPanel = new javax.swing.JPanel();
        ProcessTypeLabel = new javax.swing.JLabel();
        IOBoundOption = new javax.swing.JRadioButton();
        CPUBoundOption = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProcessTable = new javax.swing.JTable();
        ClearProcessTableButton = new javax.swing.JButton();
        AddProcessButton = new javax.swing.JButton();
        DeleteProcessButton = new javax.swing.JButton();
        ProcessNameLabel = new javax.swing.JLabel();
        IOBoundPanel = new javax.swing.JPanel();
        CyclesSatisfyExcepLabel = new javax.swing.JLabel();
        CyclesGenerateExcepLabel = new javax.swing.JLabel();
        CyclesSatisfyExcepSpinner = new javax.swing.JSpinner();
        CyclesGenerateExcepSpinner = new javax.swing.JSpinner();
        ProcessNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ProcessInstructionsTextField = new javax.swing.JTextField();
        SystemSpecificationsPanel = new javax.swing.JPanel();
        PlanningPolicyLabel = new javax.swing.JLabel();
        CicleDurationLabel = new javax.swing.JLabel();
        ActiveProcessorsTextField = new javax.swing.JLabel();
        CycleDurationTextField = new javax.swing.JTextField();
        SchedulingPolicyComboBox = new javax.swing.JComboBox<>();
        TwoProcessorsOption = new javax.swing.JRadioButton();
        ThreeProcessorsOption = new javax.swing.JRadioButton();
        TimeUnitComboBox = new javax.swing.JComboBox<>();
        ModifySpecificationsButton = new javax.swing.JButton();
        StartSimulationButton = new javax.swing.JButton();
        SimulationPanel = new javax.swing.JPanel();
        SystemPerfomanceMetricsPanel = new javax.swing.JPanel();
        SystemMetricsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalExecutionTimeLabel = new javax.swing.JLabel();
        totalClockCyclesLabel = new javax.swing.JLabel();
        completionRateLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MetricPlanningPolicyLabel = new javax.swing.JLabel();
        nProcessorsLabel = new javax.swing.JLabel();
        processesEnteredLabel = new javax.swing.JLabel();
        processesFinishedLabel = new javax.swing.JLabel();
        CPUMetricsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        IndividualCPUTable = new javax.swing.JTable();
        SimulationDetailsPanel = new javax.swing.JPanel();
        DetailsPanel = new javax.swing.JPanel();
        ExecutionModeLabel = new javax.swing.JLabel();
        ProcessesProLabel = new javax.swing.JLabel();
        GlobalClockSimulationLabel = new javax.swing.JLabel();
        ModeLabel = new javax.swing.JLabel();
        TableProcessorsPanel = new javax.swing.JPanel();
        QueuePanel = new javax.swing.JPanel();
        ReadyQueueLabel = new javax.swing.JLabel();
        BlockedQueueLabel = new javax.swing.JLabel();
        FinishedQueueLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ReadyQueueList = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        FinishedQueueList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        BlockedQueueList = new javax.swing.JList<>();
        PCBScrollPane = new javax.swing.JScrollPane();
        PCBMainPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 725));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 725));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConfigPanel.setBackground(new java.awt.Color(255, 255, 255));
        ConfigPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProcessDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        ProcessDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Process Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Geeza Pro", 3, 14))); // NOI18N
        ProcessDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProcessTypeLabel.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        ProcessTypeLabel.setText("Process Type:");
        ProcessDetailsPanel.add(ProcessTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, -1));

        ProcessTypeGroup.add(IOBoundOption);
        IOBoundOption.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        IOBoundOption.setSelected(true);
        IOBoundOption.setText("I/O Bound");
        IOBoundOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IOBoundOptionActionPerformed(evt);
            }
        });
        ProcessDetailsPanel.add(IOBoundOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        ProcessTypeGroup.add(CPUBoundOption);
        CPUBoundOption.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        CPUBoundOption.setText("CPU Bound");
        CPUBoundOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPUBoundOptionActionPerformed(evt);
            }
        });
        ProcessDetailsPanel.add(CPUBoundOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        ProcessTable.setAutoCreateRowSorter(true);
        ProcessTable.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        ProcessTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Instructions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProcessTable.setSelectionBackground(new java.awt.Color(169, 217, 241));
        ProcessTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProcessTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ProcessTable);

        ProcessDetailsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 270, 80));

        ClearProcessTableButton.setBackground(new java.awt.Color(169, 217, 241));
        ClearProcessTableButton.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        ClearProcessTableButton.setText("Clear");
        ClearProcessTableButton.setBorderPainted(false);
        ClearProcessTableButton.setOpaque(true);
        ClearProcessTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearProcessTableButtonActionPerformed(evt);
            }
        });
        ProcessDetailsPanel.add(ClearProcessTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 110, 30));

        AddProcessButton.setBackground(new java.awt.Color(169, 217, 241));
        AddProcessButton.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        AddProcessButton.setText("Add Process");
        AddProcessButton.setBorderPainted(false);
        AddProcessButton.setOpaque(true);
        AddProcessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProcessButtonActionPerformed(evt);
            }
        });
        ProcessDetailsPanel.add(AddProcessButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 200, 30));

        DeleteProcessButton.setBackground(new java.awt.Color(169, 217, 241));
        DeleteProcessButton.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        DeleteProcessButton.setText("Delete");
        DeleteProcessButton.setBorderPainted(false);
        DeleteProcessButton.setOpaque(true);
        DeleteProcessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProcessButtonActionPerformed(evt);
            }
        });
        ProcessDetailsPanel.add(DeleteProcessButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 30));

        ProcessNameLabel.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        ProcessNameLabel.setText("Process Name:");
        ProcessDetailsPanel.add(ProcessNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, -1));

        IOBoundPanel.setBackground(new java.awt.Color(255, 255, 255));
        IOBoundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CyclesSatisfyExcepLabel.setFont(new java.awt.Font("Geneva", 0, 11)); // NOI18N
        CyclesSatisfyExcepLabel.setText("Cycles to satisfy an exception:");
        IOBoundPanel.add(CyclesSatisfyExcepLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        CyclesGenerateExcepLabel.setFont(new java.awt.Font("Geneva", 0, 11)); // NOI18N
        CyclesGenerateExcepLabel.setText("Cycles to generate an exception:");
        IOBoundPanel.add(CyclesGenerateExcepLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        CyclesSatisfyExcepSpinner.setFont(new java.awt.Font("Geneva", 0, 13)); // NOI18N
        CyclesSatisfyExcepSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        IOBoundPanel.add(CyclesSatisfyExcepSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 70, 20));

        CyclesGenerateExcepSpinner.setFont(new java.awt.Font("Geneva", 0, 13)); // NOI18N
        CyclesGenerateExcepSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        IOBoundPanel.add(CyclesGenerateExcepSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 70, 20));

        ProcessDetailsPanel.add(IOBoundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 290, 110));

        ProcessNameTextField.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        ProcessNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ProcessNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ProcessNameTextFieldKeyTyped(evt);
            }
        });
        ProcessDetailsPanel.add(ProcessNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, -1));

        jLabel3.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        jLabel3.setText("Number of instructions:");
        ProcessDetailsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 240, -1));

        ProcessInstructionsTextField.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        ProcessInstructionsTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ProcessInstructionsTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ProcessInstructionsTextFieldKeyTyped(evt);
            }
        });
        ProcessDetailsPanel.add(ProcessInstructionsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, -1));

        ConfigPanel.add(ProcessDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 460));

        SystemSpecificationsPanel.setBackground(new java.awt.Color(255, 255, 255));
        SystemSpecificationsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "System Specifications", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Geeza Pro", 3, 14))); // NOI18N
        SystemSpecificationsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlanningPolicyLabel.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        PlanningPolicyLabel.setText("Planning Policy:");
        SystemSpecificationsPanel.add(PlanningPolicyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, -1));

        CicleDurationLabel.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        CicleDurationLabel.setText("Cycle Duration:");
        SystemSpecificationsPanel.add(CicleDurationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, -1));

        ActiveProcessorsTextField.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        ActiveProcessorsTextField.setText("Number of Active Processors:");
        SystemSpecificationsPanel.add(ActiveProcessorsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        CycleDurationTextField.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        CycleDurationTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CycleDurationTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CycleDurationTextFieldKeyTyped(evt);
            }
        });
        SystemSpecificationsPanel.add(CycleDurationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, -1));

        SchedulingPolicyComboBox.setFont(new java.awt.Font("Geneva", 0, 13)); // NOI18N
        SchedulingPolicyComboBox.setBorder(null);
        SystemSpecificationsPanel.add(SchedulingPolicyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, -1));

        ActiveProcessorsGroup.add(TwoProcessorsOption);
        TwoProcessorsOption.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        TwoProcessorsOption.setSelected(true);
        TwoProcessorsOption.setText("2");
        SystemSpecificationsPanel.add(TwoProcessorsOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        ActiveProcessorsGroup.add(ThreeProcessorsOption);
        ThreeProcessorsOption.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        ThreeProcessorsOption.setText("3");
        SystemSpecificationsPanel.add(ThreeProcessorsOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        TimeUnitComboBox.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        TimeUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "s", "ms" }));
        SystemSpecificationsPanel.add(TimeUnitComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        ModifySpecificationsButton.setBackground(new java.awt.Color(153, 153, 255));
        ModifySpecificationsButton.setFont(new java.awt.Font("Geneva", 1, 11)); // NOI18N
        ModifySpecificationsButton.setForeground(new java.awt.Color(255, 255, 255));
        ModifySpecificationsButton.setText("Save");
        ModifySpecificationsButton.setBorderPainted(false);
        ModifySpecificationsButton.setOpaque(true);
        ModifySpecificationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifySpecificationsButtonActionPerformed(evt);
            }
        });
        SystemSpecificationsPanel.add(ModifySpecificationsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 90, 30));

        ConfigPanel.add(SystemSpecificationsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 310, 160));

        StartSimulationButton.setBackground(new java.awt.Color(181, 241, 169));
        StartSimulationButton.setFont(new java.awt.Font("Geneva", 1, 14)); // NOI18N
        StartSimulationButton.setText("Start Simulation");
        StartSimulationButton.setBorderPainted(false);
        StartSimulationButton.setOpaque(true);
        StartSimulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartSimulationButtonActionPerformed(evt);
            }
        });
        ConfigPanel.add(StartSimulationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 310, 40));

        getContentPane().add(ConfigPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 700));

        SimulationPanel.setBackground(new java.awt.Color(255, 255, 255));
        SimulationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SystemPerfomanceMetricsPanel.setBackground(new java.awt.Color(255, 255, 255));
        SystemPerfomanceMetricsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "System Perfomance Metrics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Geeza Pro", 3, 14))); // NOI18N
        SystemPerfomanceMetricsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SystemMetricsPanel.setBackground(new java.awt.Color(255, 255, 255));
        SystemMetricsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Overall System Averages", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Geeza Pro", 3, 13))); // NOI18N
        SystemMetricsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Geeza Pro", 3, 11)); // NOI18N
        jLabel1.setText("Total Execution Time: ");
        SystemMetricsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Geeza Pro", 3, 11)); // NOI18N
        jLabel2.setText("Total Clock Cycles: ");
        SystemMetricsPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Geeza Pro", 3, 11)); // NOI18N
        jLabel4.setText("Completion Rate: ");
        SystemMetricsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        totalExecutionTimeLabel.setFont(new java.awt.Font("Geneva", 0, 10)); // NOI18N
        totalExecutionTimeLabel.setText("...");
        SystemMetricsPanel.add(totalExecutionTimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, -1));

        totalClockCyclesLabel.setFont(new java.awt.Font("Geneva", 0, 10)); // NOI18N
        totalClockCyclesLabel.setText("...");
        SystemMetricsPanel.add(totalClockCyclesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, -1));

        completionRateLabel.setFont(new java.awt.Font("Geneva", 0, 10)); // NOI18N
        completionRateLabel.setText("...");
        SystemMetricsPanel.add(completionRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, -1));

        jLabel5.setFont(new java.awt.Font("Geeza Pro", 3, 11)); // NOI18N
        jLabel5.setText("Total number of processes entered:");
        SystemMetricsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, -1));

        jLabel6.setFont(new java.awt.Font("Geeza Pro", 3, 11)); // NOI18N
        jLabel6.setText("Total number of processes finished");
        SystemMetricsPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Geeza Pro", 3, 11)); // NOI18N
        jLabel7.setText("Planning Policy: ");
        SystemMetricsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Geeza Pro", 3, 11)); // NOI18N
        jLabel8.setText("Number of Processors:");
        SystemMetricsPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        MetricPlanningPolicyLabel.setFont(new java.awt.Font("Geneva", 0, 10)); // NOI18N
        MetricPlanningPolicyLabel.setText("...");
        SystemMetricsPanel.add(MetricPlanningPolicyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 180, -1));

        nProcessorsLabel.setFont(new java.awt.Font("Geneva", 0, 10)); // NOI18N
        nProcessorsLabel.setText("...");
        SystemMetricsPanel.add(nProcessorsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, -1));

        processesEnteredLabel.setFont(new java.awt.Font("Geneva", 0, 10)); // NOI18N
        processesEnteredLabel.setText("...");
        SystemMetricsPanel.add(processesEnteredLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 60, -1));

        processesFinishedLabel.setFont(new java.awt.Font("Geneva", 0, 10)); // NOI18N
        processesFinishedLabel.setText("...");
        SystemMetricsPanel.add(processesFinishedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 60, 20));

        SystemPerfomanceMetricsPanel.add(SystemMetricsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 170));

        CPUMetricsPanel.setBackground(new java.awt.Color(255, 255, 255));
        CPUMetricsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Individual CPU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Geeza Pro", 3, 13))); // NOI18N
        CPUMetricsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IndividualCPUTable.setAutoCreateRowSorter(true);
        IndividualCPUTable.setFont(new java.awt.Font("Geneva", 1, 12)); // NOI18N
        IndividualCPUTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Total Time Used (s)", "CPU Utilization", "Handled Processes", "Processes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        IndividualCPUTable.setSelectionBackground(new java.awt.Color(169, 217, 241));
        IndividualCPUTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        IndividualCPUTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(IndividualCPUTable);

        CPUMetricsPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 140));

        SystemPerfomanceMetricsPanel.add(CPUMetricsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 610, 170));

        SimulationPanel.add(SystemPerfomanceMetricsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 940, 200));

        SimulationDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        SimulationDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simulation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Geeza Pro", 3, 14))); // NOI18N
        SimulationDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        DetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Geeza Pro", 3, 13))); // NOI18N
        DetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExecutionModeLabel.setFont(new java.awt.Font("Geeza Pro", 3, 12)); // NOI18N
        ExecutionModeLabel.setForeground(new java.awt.Color(51, 204, 0));
        ExecutionModeLabel.setText("...");
        DetailsPanel.add(ExecutionModeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 270, -1));

        ProcessesProLabel.setFont(new java.awt.Font("Geeza Pro", 3, 12)); // NOI18N
        ProcessesProLabel.setText("Current Processes Per Processor:");
        DetailsPanel.add(ProcessesProLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 380, -1));

        GlobalClockSimulationLabel.setFont(new java.awt.Font("Geeza Pro", 3, 12)); // NOI18N
        GlobalClockSimulationLabel.setText("Global Clock Cycle Number:");
        DetailsPanel.add(GlobalClockSimulationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, -1));

        ModeLabel.setFont(new java.awt.Font("Geeza Pro", 3, 12)); // NOI18N
        ModeLabel.setText("Execution Mode:");
        DetailsPanel.add(ModeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, -1));

        TableProcessorsPanel.setBackground(new java.awt.Color(255, 255, 255));
        DetailsPanel.add(TableProcessorsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 80));

        SimulationDetailsPanel.add(DetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 210));

        QueuePanel.setBackground(new java.awt.Color(255, 255, 255));
        QueuePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Queue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Geeza Pro", 3, 13))); // NOI18N
        QueuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReadyQueueLabel.setFont(new java.awt.Font("Geeza Pro", 3, 12)); // NOI18N
        ReadyQueueLabel.setText("Ready");
        QueuePanel.add(ReadyQueueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, -1));

        BlockedQueueLabel.setFont(new java.awt.Font("Geeza Pro", 3, 12)); // NOI18N
        BlockedQueueLabel.setText("Blocked");
        QueuePanel.add(BlockedQueueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 90, -1));

        FinishedQueueLabel.setFont(new java.awt.Font("Geeza Pro", 3, 12)); // NOI18N
        FinishedQueueLabel.setText("Finished");
        QueuePanel.add(FinishedQueueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 90, -1));

        ReadyQueueList.setFont(new java.awt.Font("Geneva", 0, 13)); // NOI18N
        ReadyQueueList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ReadyQueueList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ReadyQueueList.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        ReadyQueueList.setSelectionBackground(null);
        ReadyQueueList.setVerifyInputWhenFocusTarget(false);
        jScrollPane5.setViewportView(ReadyQueueList);

        QueuePanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 120));

        FinishedQueueList.setFont(new java.awt.Font("Geneva", 0, 13)); // NOI18N
        FinishedQueueList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        FinishedQueueList.setSelectionBackground(null);
        jScrollPane6.setViewportView(FinishedQueueList);

        QueuePanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 90, 120));

        BlockedQueueList.setFont(new java.awt.Font("Geneva", 0, 13)); // NOI18N
        jScrollPane2.setViewportView(BlockedQueueList);

        QueuePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 90, 120));

        SimulationDetailsPanel.add(QueuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 470, 210));

        PCBScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Process Control Blocks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Geeza Pro", 3, 13))); // NOI18N

        PCBMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        PCBMainPanel.setAutoscrolls(true);
        PCBMainPanel.add(jSeparator1);

        PCBScrollPane.setViewportView(PCBMainPanel);

        SimulationDetailsPanel.add(PCBScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 900, 220));

        SimulationPanel.add(SimulationDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 940, 460));

        getContentPane().add(SimulationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 970, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton de limpiar tabla de procesos
    private void ClearProcessTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearProcessTableButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to clear the processes?",
            "Yes",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            simulator.getGeneralQueue().clear(); 
            updateInterface(); 
            updateButtonStates();
            JOptionPane.showMessageDialog(null, "Process queue cleared successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("Process clearing canceled."); 
        }
    }//GEN-LAST:event_ClearProcessTableButtonActionPerformed

    //Boton de Iniciar Simulacion o Finalizar la Simulación
    private void StartSimulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartSimulationButtonActionPerformed
        if (CycleDurationTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a Cycle Duration.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (isSimulationFinished) { // Si la simulación ha terminado
            isSimulationActive = false;
            isSimulationFinished = false;
            stopSimulation();
            ModifySpecificationsButton.setVisible(isSimulationActive);
            //Reestablecer estilos del boton
            StartSimulationButton.setText("Start Simulation");
            StartSimulationButton.setBackground(new Color(181,241,169));
            StartSimulationButton.setForeground(Color.BLACK);
            updateButtonStates();

        } else if (isSimulationActive) { 
            int response = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to delete all simulation data?", 
        "Confirm", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE 
            );
            if (response == JOptionPane.YES_OPTION) {
                stopSimulation(); 
                isSimulationActive = false;
                ModifySpecificationsButton.setVisible(isSimulationActive);
                //Reestablecer estilos del boton
                StartSimulationButton.setText("Start Simulation");
                StartSimulationButton.setBackground(new Color(181,241,169));
                StartSimulationButton.setForeground(Color.BLACK);
                return; 
            } else {
                return;
            }  
        } else  { 
            saveToFile(); 
            updatePCBSandQueues(); 
            disablePanels(false); 
            enablePanels(true);
            // Cambiar el botón a "Stop Simulation"
            StartSimulationButton.setText("Stop Simulation");
            StartSimulationButton.setBackground(Color.RED);
            StartSimulationButton.setForeground(Color.WHITE);
            
            //Clasificar si se eligen segundos o milisegundos
            String selectedUnit = TimeUnitComboBox.getSelectedItem().toString(); //"s" o "ms"
            int cycleDuration = Integer.parseInt(CycleDurationTextField.getText());
            
            if (selectedUnit.equals("s")) {
                cycleDuration = cycleDuration * 1000;
            } else if (selectedUnit.equals("ms")) {
                cycleDuration = cycleDuration; 
            } 
            simulator.setCycleDuration(cycleDuration);
            int numProcessors = TwoProcessorsOption.isSelected() ? 2 : 3;
            simulator.setNumProcessors(numProcessors); 
            String selectedItem = SchedulingPolicyComboBox.getSelectedItem().toString();
            if (selectedItem != null) {
               SchedulingPolicy policy = SchedulingPolicy.fromString(selectedItem);
               simulator.setSchedulingPolicy(policy);
               simulator.classifyProcesses();
               //simulator.reorderAndSetReadyQueue();
            } else {
                System.out.println("No se ha seleccionado ninguna política.");
            }
            
            MainView.ExecutionModeLabel.setText("User"); //Ejecucion en modo usuario
            // Crear y empezar el temporizador
            timer = new Timer(cycleDuration, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!isSimulationActive) { 
                    timer.stop(); 
                    simulator.setGlobalCycle(0);
                    return; 
                }
                simulator.executeCycle(); 
                GlobalClockSimulationLabel.setText("Global Clock Cycle Number: " + simulator.getGlobalCycle());
                updatePCBSandQueues(); 
                TableProcessorsPanel.removeAll();
                TableProcessors table = new TableProcessors(simulator.updateProcessTable());
                TableProcessorsPanel.add(table);
                }
            });

            timer.start(); // Iniciar el temporizador
            isSimulationActive = true; 
            ModifySpecificationsButton.setVisible(isSimulationActive);
            updatePCBSandQueues();
        }
    }//GEN-LAST:event_StartSimulationButtonActionPerformed
    
    private void IOBoundOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IOBoundOptionActionPerformed
        disableJPanel(IOBoundPanel,true);
    }//GEN-LAST:event_IOBoundOptionActionPerformed

    //Añadir proceso
    private void AddProcessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProcessButtonActionPerformed
       // Validar campos
        String message = "Attention: Please fill in all required fields."; 
        if (ProcessInstructionsTextField.getText().isEmpty() || ProcessNameTextField.getText().isEmpty()  ) {
            JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.WARNING_MESSAGE);
            return; 
        }

        String name = ProcessNameTextField.getText();
        if (simulator.getGeneralQueue().containsName(name)) { 
            JOptionPane.showMessageDialog(null, "A process with that name already exists.", "Error", JOptionPane.WARNING_MESSAGE);
            return; 
        }

        boolean isCpuBound = CPUBoundOption.isSelected();
        int exceptionCycle = (int) CyclesGenerateExcepSpinner.getValue();
        int satisfactionCycle = (int) CyclesSatisfyExcepSpinner.getValue();
        int numberOfInstructions = Integer.parseInt(ProcessInstructionsTextField.getText().trim());
        
        // Crear el proceso
        Process process = new Process(name, numberOfInstructions, isCpuBound, exceptionCycle, satisfactionCycle, simulator); //id se asigna automatico
        simulator.getReadyQueue().add(process);
        // Agregar el proceso al simulador
 //       ProcessQueue readyQueue = new ProcessQueue(3);
        simulator.addProcess(process);

        DefaultTableModel modelo = (DefaultTableModel) ProcessTable.getModel();
        modelo.addRow(new Object[]{process.getName(), isCpuBound ? "CPU Bound" : "I/O Bound", process.getInstructions()});
        JOptionPane.showMessageDialog(null, "Process Created!", "Success", JOptionPane.INFORMATION_MESSAGE);
        resetFields();
        updateButtonStates();
    }//GEN-LAST:event_AddProcessButtonActionPerformed

    //Borrar un proceso de la cola
    private void DeleteProcessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProcessButtonActionPerformed
       Process selectedProcess = getSelectedProcess(); 
        if (selectedProcess != null) {
            if (simulator.getGeneralQueue().remove(selectedProcess)) { 
                updateInterface();
                JOptionPane.showMessageDialog(null, "Process deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                updateButtonStates();
            } else {
                JOptionPane.showMessageDialog(null, "Process not found in the queue.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No process selected to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteProcessButtonActionPerformed

    private void CPUBoundOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPUBoundOptionActionPerformed
        disableJPanel(IOBoundPanel,false);
        resetSpinners();
    }//GEN-LAST:event_CPUBoundOptionActionPerformed

    private void ProcessInstructionsTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProcessInstructionsTextFieldKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_ProcessInstructionsTextFieldKeyTyped

    private void CycleDurationTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CycleDurationTextFieldKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_CycleDurationTextFieldKeyTyped

    private void ProcessNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProcessNameTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c) && c != ' ') {
            evt.consume(); 
        }
    }//GEN-LAST:event_ProcessNameTextFieldKeyTyped

    private void ModifySpecificationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifySpecificationsButtonActionPerformed
        //Cambiar los argumentos de System Specifications
        simulator.classifyProcesses();
        String selectedItem = SchedulingPolicyComboBox.getSelectedItem().toString();
            if (selectedItem != null) {
                SchedulingPolicy policy = SchedulingPolicy.fromString(selectedItem);
                simulator.setSchedulingPolicy(policy);
                //simulator.reorderAndSetReadyQueue(); 
                System.out.println("Selected Policy: " + policy);
            } else {
                System.out.println("No se ha seleccionado ninguna política.");
            }
    }//GEN-LAST:event_ModifySpecificationsButtonActionPerformed
    
    
    //FUNCIONES
    
    // Actualizar la tabla de procesos listos
    public void updateInterface() {
        DefaultTableModel modeloListos = (DefaultTableModel) ProcessTable.getModel();
        modeloListos.setRowCount(0);
        for (int i = 0; i < simulator.getGeneralQueue().size(); i++) { //revisar esto
            Process process = simulator.getGeneralQueue().get(i);
            modeloListos.addRow(new Object[]{process.getName(), process.isCpuBound() ? "CPU Bound" : "I/O Bound", process.getInstructions()});
        }
    }
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            new MainView().setVisible(true);
        });
    }
    
    
    //Paneles deshabilitados antes de la simulación
    public void enablePanels(boolean value) {
        disableJPanel(SimulationDetailsPanel, value);
        disableJPanel(DetailsPanel,value);
        disableJPanel(QueuePanel,value);
        disableJPanel(PCBMainPanel,value);
        ReadyQueueList.setEnabled(value);
        BlockedQueueList.setEnabled(value);
        FinishedQueueList.setEnabled(value);
    } 
    
    //Paneles deshabilitados al iniciar la simulación
    public void disablePanels(boolean value) {
        disableJPanel(ProcessDetailsPanel, value);
        disableJPanel(IOBoundPanel, value);
        ProcessTable.setEnabled(value);
    }
    
    //Funcion para activar y desactivar paneles de estadisticas
    public void updatePanelVisibility(boolean isSimulationFinished) {
        if (!isSimulationFinished) {
            SystemMetricsPanel.setVisible(false);
            CPUMetricsPanel.setVisible(false);
        } else {
            SystemMetricsPanel.setVisible(true);
            CPUMetricsPanel.setVisible(true);
        }
    }
    
    
    //Función para deshabilitar paneles
    public void disableJPanel(JPanel panel, boolean value) {
        for (Component a : panel.getComponents()) {
            a.setEnabled(value);
        }
    }
    
    //Devolver spinner a su valor original
    private void resetSpinners() {
        CyclesGenerateExcepSpinner.setValue(1);
        CyclesSatisfyExcepSpinner.setValue(1);
    }
    
    //devolver campos a su valor original
    private void resetFields() {
        ProcessInstructionsTextField.setText("");
        ProcessNameTextField.setText("");
        resetSpinners();
    }
    
    //Actualizar el estado de los botones
    private void updateButtonStates() {
        boolean isQueueEmpty = simulator.getGeneralQueue().isEmpty();
        ClearProcessTableButton.setEnabled(!isQueueEmpty);
        DeleteProcessButton.setEnabled(!isQueueEmpty);
        StartSimulationButton.setEnabled(!isQueueEmpty);
    }
    
    //Tomar el proceso seleccionado en tabla
    private Process getSelectedProcess() {
        int selectedRow = ProcessTable.getSelectedRow(); 
        if (selectedRow >= 0) {
            return simulator.getGeneralQueue().get(selectedRow);
        }
        return null; 
    }
    
    //Finalizar la simulacion de forma arbitraria
    private void stopSimulation() {
        //Limpiar listas
        simulator.reset();
        simulator.getGeneralQueue().clear(); //Limpiar toda la lista de procesos
        simulator.getReadyQueue().clear(); //Limpiar la lista de listos
        simulator.getBlockedQueue().clear(); //Limpiar la lista de bloqueados
        simulator.getFinishedQueue().clear(); //Limpiar la lista de terminados
        updatePCBSandQueues();
        updatePanelVisibility(isSimulationFinished);
        //Limpiar interfaz
        ExecutionModeLabel.setText("");
        updateInterface(); //Limpia la tabla de procesos
        updateButtonStates(); //Cambia el estado de los botones 
        PCBMainPanel.removeAll(); //Limpiar PCBs
        TableProcessorsPanel.removeAll();//Limpiar tabla de procesadores por proceso
        GlobalClockSimulationLabel.setText("Global Clock Cycle Number: 0");
        ReadyQueueList.setModel(new DefaultListModel<>());
        BlockedQueueList.setModel(new DefaultListModel<>());
        FinishedQueueList.setModel(new DefaultListModel<>());
        disableJPanel(IOBoundPanel, IOBoundOption.isSelected());
        disableJPanel(ProcessDetailsPanel, true);
        ProcessTable.setEnabled(true); 
        enablePanels(false);
    }
    
    //Mostrar o actualizar PCBs
    public void updatePCBSandQueues() {
    // Clasificar los procesos en las colas correspondientes
    simulator.classifyProcesses();
    // Crear nuevos modelos para las listas de la interfaz
    DefaultListModel<String> readyListModel = new DefaultListModel<>();
    DefaultListModel<String> blockedListModel = new DefaultListModel<>();
    DefaultListModel<String> finishedListModel = new DefaultListModel<>();

    // Obtener los nombres de los procesos en cada cola y agregarlos a los modelos
    for (int i = 0; i < simulator.getReadyQueue().size(); i++) {
        Process process = simulator.getReadyQueue().get(i);
        readyListModel.addElement(process.getName());
    }

    for (int i = 0; i < simulator.getBlockedQueue().size(); i++) {
        Process process = simulator.getBlockedQueue().get(i);
        blockedListModel.addElement(process.getName());
    }

    for (int i = 0; i < simulator.getFinishedQueue().size(); i++) {
        Process process = simulator.getFinishedQueue().get(i);
        finishedListModel.addElement(process.getName());
    }

    // Asignar los nuevos modelos a las listas de la interfaz
    ReadyQueueList.setModel(readyListModel);
    BlockedQueueList.setModel(blockedListModel);
    FinishedQueueList.setModel(finishedListModel);

    // Actualizar los PCBs en la interfaz gráfica
    PCBMainPanel.removeAll();
    ProcessQueue allProcess = simulator.getGeneralQueue();
    if (allProcess.size() > 0) {
        for (int i = 0; i < allProcess.size(); i++) {
            Process process = allProcess.get(i);
            if (process != null) {
                ProcessPCB processPanel = new ProcessPCB(process);
                PCBMainPanel.add(processPanel);
            }
        }
    }
    PCBMainPanel.revalidate();
    PCBMainPanel.repaint();
}

    //Txt config
    private void saveToFile() {
    String filename = System.getProperty("user.dir") + "/simulation_results.txt";
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename))) {
        writer.write("#Simulation Data");
        writer.newLine();

        writer.write("#PROCESS");
        writer.newLine();

        simulator.getGeneralQueue().iterateProcesses(writer);

        writer.newLine();
        writer.write("#CONFIG");
        writer.newLine();

        writer.write("Cycle Duration: " + CycleDurationTextField.getText().trim());
        writer.newLine();
        writer.write("Number of Active Processors: " + 
                     (TwoProcessorsOption.isSelected() ? "2" : "3"));
        writer.newLine();
        writer.write("Planning Policy: " + SchedulingPolicyComboBox.getSelectedItem());
        writer.newLine();

        JOptionPane.showMessageDialog(null, "Your simulation data has been saved in " + filename);
    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error! Data not saved!");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ActiveProcessorsGroup;
    private javax.swing.JLabel ActiveProcessorsTextField;
    private javax.swing.JButton AddProcessButton;
    private javax.swing.JLabel BlockedQueueLabel;
    private javax.swing.JList<String> BlockedQueueList;
    private javax.swing.JRadioButton CPUBoundOption;
    private javax.swing.JPanel CPUMetricsPanel;
    private javax.swing.JLabel CicleDurationLabel;
    private javax.swing.JButton ClearProcessTableButton;
    private javax.swing.JPanel ConfigPanel;
    private javax.swing.JTextField CycleDurationTextField;
    private javax.swing.JLabel CyclesGenerateExcepLabel;
    private javax.swing.JSpinner CyclesGenerateExcepSpinner;
    private javax.swing.JLabel CyclesSatisfyExcepLabel;
    private javax.swing.JSpinner CyclesSatisfyExcepSpinner;
    private javax.swing.JButton DeleteProcessButton;
    private javax.swing.JPanel DetailsPanel;
    public static javax.swing.JLabel ExecutionModeLabel;
    private javax.swing.JLabel FinishedQueueLabel;
    private javax.swing.JList<String> FinishedQueueList;
    public javax.swing.JLabel GlobalClockSimulationLabel;
    private javax.swing.JRadioButton IOBoundOption;
    private javax.swing.JPanel IOBoundPanel;
    public javax.swing.JTable IndividualCPUTable;
    public javax.swing.JLabel MetricPlanningPolicyLabel;
    private javax.swing.JLabel ModeLabel;
    private javax.swing.JButton ModifySpecificationsButton;
    private javax.swing.JPanel PCBMainPanel;
    private javax.swing.JScrollPane PCBScrollPane;
    private javax.swing.JLabel PlanningPolicyLabel;
    private javax.swing.JPanel ProcessDetailsPanel;
    private javax.swing.JTextField ProcessInstructionsTextField;
    private javax.swing.JLabel ProcessNameLabel;
    private javax.swing.JTextField ProcessNameTextField;
    private javax.swing.JTable ProcessTable;
    private javax.swing.ButtonGroup ProcessTypeGroup;
    private javax.swing.JLabel ProcessTypeLabel;
    private javax.swing.JLabel ProcessesProLabel;
    private javax.swing.JPanel QueuePanel;
    private javax.swing.JLabel ReadyQueueLabel;
    private javax.swing.JList ReadyQueueList;
    private javax.swing.JComboBox<String> SchedulingPolicyComboBox;
    private javax.swing.JPanel SimulationDetailsPanel;
    private javax.swing.JPanel SimulationPanel;
    public javax.swing.JButton StartSimulationButton;
    private javax.swing.JPanel SystemMetricsPanel;
    private javax.swing.JPanel SystemPerfomanceMetricsPanel;
    private javax.swing.JPanel SystemSpecificationsPanel;
    private javax.swing.JPanel TableProcessorsPanel;
    private javax.swing.JRadioButton ThreeProcessorsOption;
    private javax.swing.JComboBox<String> TimeUnitComboBox;
    private javax.swing.JRadioButton TwoProcessorsOption;
    public javax.swing.JLabel completionRateLabel;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel nProcessorsLabel;
    public javax.swing.JLabel processesEnteredLabel;
    public javax.swing.JLabel processesFinishedLabel;
    public javax.swing.JLabel totalClockCyclesLabel;
    public javax.swing.JLabel totalExecutionTimeLabel;
    // End of variables declaration//GEN-END:variables
}
